FROM python:3.9

WORKDIR /code

COPY ./requirements-flask.txt /code/requirements.txt
COPY *.whl /code/

RUN pip install /code/*.whl
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./src/python /code

WORKDIR /code/app

CMD ["gunicorn", "--conf", "gunicorn_conf.py", "--bind", "0.0.0.0:80", "wsgi:app"]