version: '3.6'
services:
  flask:
    build:
      context: .
      dockerfile: dockerfile-flask
    ports:
      - 80:80
    depends_on:
      - iris
    volumes:
      - ./src/python:/code
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 51773:1972
      - 57777:52773
      - 53773
    volumes:
      - ./:/irisdev/app
  db:
    image: postgres:12.2
    hostname: db
    environment:
        POSTGRES_DB: DemoData
        POSTGRES_PASSWORD: DemoData
        POSTGRES_USER: DemoData
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "DemoData"]
        interval: 30s
        timeout: 30s
        retries: 3
    ports:
    - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/